[theme]
base = "light"
primaryColor = "#122ba6"
textColor = "#444d6d"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
